apiVersion: apps/v1
kind: Deployment
metadata:
  name: denis-dep
  labels:
    app: denis-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: denis-app
  template:
    metadata:
      labels:
        app: denis-app
    spec:
      containers:
      - name: k8sphp
        image: adv4000/k8sphp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: denis-service
spec:
  selector:
    app: denis-app
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80